package br.com.dpplus.fintech.domain.enums;

public enum TipoSugestao {
    RESERVA_EMERGENCIA, REDUCAO_GASTOS, ALOCACAO_FIXA, ALOCACAO_EQUILIBRADA,
    ALOCACAO_ARROJADA, FLUXO_CAIXA_NEGATIVO, DIVERSIFICACAO_INTERNACIONAL
}
